
import com.sun.istack.internal.logging.Logger;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vira Meliana
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNIS = new javax.swing.JTextField();
        rdLaki = new javax.swing.JRadioButton();
        rdPerempuan = new javax.swing.JRadioButton();
        txtNama = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM BIODATA SISWA SMK TELKOM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 400, 50);

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("The Real Informatic Schools");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 50, 260, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 910, 110);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 500, 110, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Isian Data Siswa");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 130, 110, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("NIS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 160, 110, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Nama");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 230, 110, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Kelas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 360, 110, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 430, 110, 40);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(40, 470, 190, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Jenis Kelamin");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 300, 110, 40);
        getContentPane().add(txtNIS);
        txtNIS.setBounds(40, 200, 190, 30);

        rdLaki.setBackground(new java.awt.Color(102, 204, 255));
        buttonGroup1.add(rdLaki);
        rdLaki.setText("Laki-Laki");
        getContentPane().add(rdLaki);
        rdLaki.setBounds(40, 340, 90, 23);

        rdPerempuan.setBackground(new java.awt.Color(102, 204, 255));
        buttonGroup1.add(rdPerempuan);
        rdPerempuan.setText("Perempuan");
        getContentPane().add(rdPerempuan);
        rdPerempuan.setBounds(129, 340, 110, 23);
        getContentPane().add(txtNama);
        txtNama.setBounds(40, 270, 190, 30);
        getContentPane().add(txtKelas);
        txtKelas.setBounds(40, 400, 190, 30);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 540, 200, 96);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setLayout(null);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 40, 240, 490);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 130, 240, 520);

        btnEdit.setBackground(new java.awt.Color(255, 102, 102));
        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(710, 160, 100, 40);

        btnSave.setBackground(new java.awt.Color(255, 102, 102));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(290, 160, 80, 40);

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(380, 160, 100, 40);

        btnClear.setBackground(new java.awt.Color(255, 102, 102));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(490, 160, 100, 40);

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(280, 130, 540, 0);

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));
        jPanel4.setLayout(null);

        btnRefresh.setBackground(new java.awt.Color(255, 102, 102));
        btnRefresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel4.add(btnRefresh);
        btnRefresh.setBounds(320, 30, 100, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(280, 130, 540, 100);

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));
        jPanel5.setLayout(null);

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "JenisKelamin", "Kelas", "Email", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbData);
        if (tbData.getColumnModel().getColumnCount() > 0) {
            tbData.getColumnModel().getColumn(0).setResizable(false);
            tbData.getColumnModel().getColumn(1).setResizable(false);
            tbData.getColumnModel().getColumn(2).setResizable(false);
            tbData.getColumnModel().getColumn(3).setResizable(false);
            tbData.getColumnModel().getColumn(4).setResizable(false);
            tbData.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(30, 20, 452, 330);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(290, 270, 510, 370);

        setBounds(0, 0, 844, 707);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if ("".equals(txtNIS.getText()) || "".equals(txtAlamat.getText()) || "".equals(txtKelas.getText()) || "".equals(txtNama.getText()) || "".equals(txtEmail.getText()))
                {JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
                
                }else {
        String JK = "";
        if (rdLaki.isSelected()){
        JK = "L";
        }else{
        JK = "P";
        }
        String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat)" + "VALUES ('"+txtNIS.getText()+"','"+txtNama.getText()+"','"+JK+"','"+txtKelas.getText()+"','"+txtEmail.getText()+"','"+txtAlamat.getText()+"')";
        
        int status = KoneksiDB.execute(SQL);
        if (status == 1 ){
        JOptionPane.showMessageDialog(this, "Data Berhasil di tambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
        JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Sukses", JOptionPane.WARNING_MESSAGE);
        }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int baris = tbData.getSelectedRow();
        if (baris!= -1){
        String NIS = tbData.getValueAt(baris,0).toString();
        String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
        int status = KoneksiDB.execute(SQL);
        if(status == 1) {
        JOptionPane.showMessageDialog(this,"Data berhasil dihapus","Sukses", JOptionPane.INFORMATION_MESSAGE);
        
        }
        else {
        JOptionPane.showMessageDialog(this, "Data Gagal di hapus","Gagal",JOptionPane.ERROR_MESSAGE);
        }
        
        } else {
        JOptionPane.showMessageDialog(this,"Pilih Baris terlebih dahulu","Error", JOptionPane.WARNING_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
txtNama.setText("");
txtKelas.setText("");
txtNIS.setText("");
buttonGroup1.clearSelection();
txtEmail.setText("");
txtAlamat.setText("");


        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
     selectData();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
if ("".equals(txtNIS.getText()) ||"".equals(txtAlamat.getText()) || "".equals(txtKelas.getText())||"".equals(txtNama.getText()) || "".equals(txtEmail.getText())){
JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);
}
else {
String JK  = "";
if (rdLaki.isSelected()){
JK = "L";
}else {
JK = "P";
}
String SQL = "UPDATE t_siswa SET " + "WHERE NamaSiswa = '"+txtNama.getText()+"',"+"WHERE JenisKelamin = '" + JK +"',"+
        "WHERE Kelas = '"+txtKelas.getText()+"',"+"WHERE Email = '"+txtEmail.getText()+"',"+
        "WHERE Alamat= '"+txtAlamat.getText()+"',"+"WHERE NIS = '"+txtNIS.getText()+"'";
int status = KoneksiDB.execute(SQL);
if (status == 0){
JOptionPane.showMessageDialog(this, "Data Berhasil Update","Sukses", JOptionPane.INFORMATION_MESSAGE);
selectData();
}
else{
JOptionPane.showMessageDialog(this,"Data Gagal di Update","Gagal",JOptionPane.WARNING_MESSAGE);
}}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
int baris = tbData.getSelectedRow();
if(baris!= -1) {
txtNIS.setText(tbData.getValueAt(baris,0).toString());
txtNama.setText(tbData.getValueAt(baris,1).toString());
if ("Laki-laki".equals(tbData.getValueAt(baris,2).toString())){
rdLaki.setSelected(true);
} else {
rdPerempuan.setSelected(true);
}
txtKelas.setText(tbData.getValueAt(baris,3).toString());
txtEmail.setText(tbData.getValueAt(baris,4).toString());
txtAlamat.setText(tbData.getValueAt(baris,5).toString());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdLaki;
    private javax.swing.JRadioButton rdPerempuan;
    private javax.swing.JTable tbData;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNIS;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    public void selectData() {
    String kolom[] = {"NIS", "NamaSiswa","JenisKelamin","Kelas","Email","Alamat"};
    DefaultTableModel dtm = new DefaultTableModel(null,kolom);
    String SQL = "SELECT * FROM t_siswa";
    ResultSet rs = KoneksiDB.executeQuery(SQL);
    try {
    while (rs.next()){
    String NIS = rs.getString(1);
    String NamaSiswa = rs.getString(2);
    String JenisKelamin = "";
    if ("L".equals(rs.getString(3)))
    {
    JenisKelamin = "LakiLaki";
    
    }else {
    JenisKelamin = "Perempuan";
    }
    String Kelas = rs.getString(4);
    String Email = rs.getString(5);
    String Alamat = rs.getString(6);
    String data[]= {NIS, NamaSiswa, JenisKelamin,Kelas,Email,Alamat};
    dtm.addRow(data);
    }
    }   catch (SQLException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    tbData.setModel(dtm);
            }

    private DefaultTableModel DefaultTabelModel(Object object, String[] kolom) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
